<?php require_once __DIR__ . '/auth.php'; requireLogin(); require_once __DIR__ . '/../backend/config.php';
$pdo = getDB();
$portfolioCount = $pdo->query("SELECT COUNT(*) FROM portfolio_items")->fetchColumn();
$videoCount = $pdo->query("SELECT COUNT(*) FROM videos")->fetchColumn();
$contactCount = $pdo->query("SELECT COUNT(*) FROM contacts")->fetchColumn();
$estimateCount = $pdo->query("SELECT COUNT(*) FROM estimates")->fetchColumn();
$portfolioItems = $pdo->query("SELECT * FROM portfolio_items ORDER BY id DESC LIMIT 50")->fetchAll();
$videos = $pdo->query("SELECT * FROM videos ORDER BY id DESC LIMIT 50")->fetchAll();
$contacts = $pdo->query("SELECT * FROM contacts ORDER BY id DESC LIMIT 20")->fetchAll();
$estimates = $pdo->query("SELECT * FROM estimates ORDER BY id DESC LIMIT 20")->fetchAll();
$flash = $_SESSION['flash'] ?? null; unset($_SESSION['flash']);
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Admin Dashboard</title><link rel="stylesheet" href="style.css"></head><body>
<div class="navbar"><h2>Borondala Admin</h2><div><a href="../" style="margin-right:16px;">View Site</a><a href="logout.php">Logout</a></div></div>
<div class="container">
<?php if ($flash): ?><div class="alert alert-<?= $flash['type'] ?>"><?= htmlspecialchars($flash['message']) ?></div><?php endif; ?>
<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:16px;margin-bottom:24px;">
<div style="background:#141414;border:1px solid #222;border-radius:8px;padding:16px;text-align:center;"><div style="font-size:2rem;color:#c9a96e;"><?= $portfolioCount ?></div><div style="font-size:.8rem;color:#888;">Photos</div></div>
<div style="background:#141414;border:1px solid #222;border-radius:8px;padding:16px;text-align:center;"><div style="font-size:2rem;color:#c9a96e;"><?= $videoCount ?></div><div style="font-size:.8rem;color:#888;">Videos</div></div>
<div style="background:#141414;border:1px solid #222;border-radius:8px;padding:16px;text-align:center;"><div style="font-size:2rem;color:#c9a96e;"><?= $contactCount ?></div><div style="font-size:.8rem;color:#888;">Messages</div></div>
<div style="background:#141414;border:1px solid #222;border-radius:8px;padding:16px;text-align:center;"><div style="font-size:2rem;color:#c9a96e;"><?= $estimateCount ?></div><div style="font-size:.8rem;color:#888;">Estimates</div></div>
</div>
<div class="tabs"><button class="tab active" data-tab="portfolio">Photos (<?= $portfolioCount ?>)</button><button class="tab" data-tab="videos">Videos (<?= $videoCount ?>)</button><button class="tab" data-tab="contacts">Messages (<?= $contactCount ?>)</button><button class="tab" data-tab="estimates">Estimates (<?= $estimateCount ?>)</button></div>
<div class="tab-content active" id="tab-portfolio"><div style="margin-bottom:16px;"><a href="add_portfolio.php" class="btn btn-sm">+ Add Photo</a></div>
<?php if (count($portfolioItems)>0): ?><div class="grid"><?php foreach ($portfolioItems as $item): ?><div class="card"><img src="../<?= htmlspecialchars($item['image_path']) ?>" alt="<?= htmlspecialchars($item['alt_text']) ?>" loading="lazy"><div class="card-body"><h4><?= htmlspecialchars($item['title']) ?></h4><div class="meta"><?= htmlspecialchars($item['category']) ?> | Order: <?= $item['display_order'] ?></div><div class="card-actions"><a href="delete.php?type=portfolio&id=<?= $item['id'] ?>" class="btn btn-sm btn-danger" onclick="return confirm('Delete?')">Delete</a></div></div></div><?php endforeach; ?></div>
<?php else: ?><p style="color:#666;">No photos. <a href="add_portfolio.php" style="color:#c9a96e;">Add one.</a></p><?php endif; ?></div>
<div class="tab-content" id="tab-videos"><div style="margin-bottom:16px;"><a href="add_video.php" class="btn btn-sm">+ Add Video</a></div>
<?php if (count($videos)>0): ?><div class="grid"><?php foreach ($videos as $v): ?><div class="card"><?php $thumb=$v['thumbnail_url']; if(!$thumb && preg_match('/(?:youtube\.com\/(?:watch\?v=|embed\/|shorts\/)|youtu\.be\/)([a-zA-Z0-9_-]+)/',$v['youtube_url'],$m)) $thumb='https://img.youtube.com/vi/'.$m[1].'/maxresdefault.jpg'; ?>
<?php if($thumb): ?><img src="<?= htmlspecialchars($thumb) ?>" alt="" loading="lazy" style="height:120px;"><?php endif; ?><div class="card-body"><h4><?= htmlspecialchars($v['title']) ?></h4><div class="meta"><?= htmlspecialchars($v['category']) ?></div><div class="card-actions"><a href="delete.php?type=video&id=<?= $v['id'] ?>" class="btn btn-sm btn-danger" onclick="return confirm('Delete?')">Delete</a></div></div></div><?php endforeach; ?></div>
<?php else: ?><p style="color:#666;">No videos. <a href="add_video.php" style="color:#c9a96e;">Add one.</a></p><?php endif; ?></div>
<div class="tab-content" id="tab-contacts"><?php if (count($contacts)>0): ?><div style="overflow-x:auto;"><table style="width:100%;border-collapse:collapse;font-size:.85rem;"><thead><tr style="border-bottom:1px solid #222;text-align:left;"><th style="padding:8px;">Name</th><th style="padding:8px;">Email</th><th style="padding:8px;">Event</th><th style="padding:8px;">Date</th><th style="padding:8px;">Message</th><th style="padding:8px;">Received</th><th style="padding:8px;"></th></tr></thead><tbody><?php foreach ($contacts as $c): ?><tr style="border-bottom:1px solid #1a1a1a;"><td style="padding:8px;"><?= htmlspecialchars($c['name']) ?></td><td style="padding:8px;"><?= htmlspecialchars($c['email']) ?></td><td style="padding:8px;"><?= htmlspecialchars($c['event_type']) ?></td><td style="padding:8px;"><?= htmlspecialchars($c['event_date']) ?></td><td style="padding:8px;max-width:200px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><?= htmlspecialchars($c['message']) ?></td><td style="padding:8px;color:#666;font-size:.75rem;"><?= $c['created_at'] ?></td><td style="padding:8px;"><a href="delete.php?type=contact&id=<?= $c['id'] ?>" class="btn btn-sm btn-danger" onclick="return confirm('Delete?')">Delete</a></td></tr><?php endforeach; ?></tbody></table></div>
<?php else: ?><p style="color:#666;">No messages yet.</p><?php endif; ?></div>
<div class="tab-content" id="tab-estimates"><?php if (count($estimates)>0): ?><div style="overflow-x:auto;"><table style="width:100%;border-collapse:collapse;font-size:.85rem;"><thead><tr style="border-bottom:1px solid #222;text-align:left;"><th style="padding:8px;">Name</th><th style="padding:8px;">Email</th><th style="padding:8px;">Phone</th><th style="padding:8px;">Event</th><th style="padding:8px;">Date</th><th style="padding:8px;">Budget</th><th style="padding:8px;">Services</th><th style="padding:8px;">Details</th><th style="padding:8px;">Received</th><th style="padding:8px;"></th></tr></thead><tbody><?php foreach ($estimates as $e): ?><tr style="border-bottom:1px solid #1a1a1a;"><td style="padding:8px;"><?= htmlspecialchars($e['name']) ?></td><td style="padding:8px;"><?= htmlspecialchars($e['email']) ?></td><td style="padding:8px;"><?= htmlspecialchars($e['phone']) ?></td><td style="padding:8px;"><?= htmlspecialchars($e['event_type']) ?></td><td style="padding:8px;"><?= htmlspecialchars($e['event_date']) ?></td><td style="padding:8px;"><?= htmlspecialchars($e['budget']) ?></td><td style="padding:8px;"><?= htmlspecialchars($e['services']) ?></td><td style="padding:8px;max-width:150px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"><?= htmlspecialchars($e['details']) ?></td><td style="padding:8px;color:#666;font-size:.75rem;"><?= $e['created_at'] ?></td><td style="padding:8px;"><a href="delete.php?type=estimate&id=<?= $e['id'] ?>" class="btn btn-sm btn-danger" onclick="return confirm('Delete?')">Delete</a></td></tr><?php endforeach; ?></tbody></table></div>
<?php else: ?><p style="color:#666;">No estimates yet.</p><?php endif; ?></div>
</div>
<script>document.querySelectorAll('.tab').forEach(t=>{t.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(t2=>t2.classList.remove('active'));document.querySelectorAll('.tab-content').forEach(tc=>tc.classList.remove('active'));t.classList.add('active');document.getElementById('tab-'+t.dataset.tab).classList.add('active')})})</script>
</body></html>
